# Generated by cpp11: do not edit by hand

p_gradUsparse <- function(indices, Xm, Gm, CUm, OUm, Cm, idx, tau, Rowm, Colm) {
  .Call(`_CMF_p_gradUsparse`, indices, Xm, Gm, CUm, OUm, Cm, idx, tau, Rowm, Colm)
}

p_updatePseudoData <- function(indices, U1m, U2m, Rv, Cv) {
  .Call(`_CMF_p_updatePseudoData`, indices, U1m, U2m, Rv, Cv)
}

p_updateTau <- function(indices, Xm, U1m, U2m, cov1m, cov2m, Rv, Cv, nu1v, nu2v) {
  .Call(`_CMF_p_updateTau`, indices, Xm, U1m, U2m, cov1m, cov2m, Rv, Cv, nu1v, nu2v)
}

p_updateMean <- function(indices, Xm, U1m, U2m, idx, Mv) {
  .Call(`_CMF_p_updateMean`, indices, Xm, U1m, U2m, idx, Mv)
}

p_covUsparse <- function(indices, Cm, OUm, OCm, idx, tau) {
  .Call(`_CMF_p_covUsparse`, indices, Cm, OUm, OCm, idx, tau)
}
